name: Checks
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: 'src'
          extensions: 'h,c'
          clangFormatVersion: 17
      - name: Execute the unit tests
        run: |
          autoreconf -i
          ./configure
          make unit
          ./unit

