name: Checks
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Execute the checks
        run: |
          sudo apt-get install libcriterion-dev
          sudo apt-get clang-format
          autoreconf -i
          ./configure
          make check

