name: Checks
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - name: Run clang-format style
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '13'
          check-path: 'src'
      - name: Execute the unit tests
        run: |
          make unit
          ./unit

